### ISSUE TITLE
[Question]: `amazon/dynamodb-local:2.5.0` fails to start on M1

### ISSUE THREAD

**Issue by Maxwell2022** [amazonlinux/container-images#108]
### Product

Not Specific / Don't Know

### What is your question?

I noticed this new version of `amazon/dynamodb-local` `v2.5.0` (18 hours ago).
This version fails to start on Apple Silicone (M1) with the following error in the container:

```
2024-05-29 17:05:23 Initializing DynamoDB Local with the following configuration:
2024-05-29 17:05:23 Port:       8000
2024-05-29 17:05:23 InMemory:   false
2024-05-29 17:05:23 Version:    2.5.0
2024-05-29 17:05:23 DbPath:     ./data
2024-05-29 17:05:23 SharedDb:   true
2024-05-29 17:05:23 shouldDelayTransientStatuses:       false
2024-05-29 17:05:23 CorsParams: null
2024-05-29 17:05:23 
2024-05-29 17:05:39 May 29, 2024 7:05:38 AM com.almworks.sqlite4java.Internal log
2024-05-29 17:05:39 WARNING: [sqlite] SQLiteDBAccess$1@21e7144f: job exception
2024-05-29 17:05:39 com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() ALTER TABLE dm ADD COLUMN MaxReadRequestUnits INTEGER DEFAULT 0ADD COLUMN MaxWriteRequestUnits INTEGER DEFAULT 0; [unrecognized token: "0ADD"]
2024-05-29 17:05:39     at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1436)
2024-05-29 17:05:39     at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:580)
2024-05-29 17:05:39     at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:635)
2024-05-29 17:05:39     at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:622)
2024-05-29 17:05:39     at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.AmazonDynamoDBOfflineSQLiteJob.getPreparedStatement(AmazonDynamoDBOfflineSQLiteJob.java:159)
2024-05-29 17:05:39     at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$1.doWork(SQLiteDBAccess.java:531)
2024-05-29 17:05:39     at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$1.doWork(SQLiteDBAccess.java:406)
2024-05-29 17:05:39     at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.AmazonDynamoDBOfflineSQLiteJob.job(AmazonDynamoDBOfflineSQLiteJob.java:117)
2024-05-29 17:05:39     at com.almworks.sqlite4java.SQLiteJob.execute(SQLiteJob.java:372)
2024-05-29 17:05:39     at com.almworks.sqlite4java.SQLiteQueue.executeJob(SQLiteQueue.java:534)
2024-05-29 17:05:39     at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:667)
2024-05-29 17:05:39     at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
2024-05-29 17:05:39     at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
2024-05-29 17:05:39     at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
2024-05-29 17:05:39     at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-29 17:05:39 
```

version `2.4.0` has no problem, starts without errors:

```
2024-05-29 17:19:26 Initializing DynamoDB Local with the following configuration:
2024-05-29 17:19:26 Port:       8000
2024-05-29 17:19:26 InMemory:   false
2024-05-29 17:19:26 Version:    2.4.0
2024-05-29 17:19:26 DbPath:     ./data
2024-05-29 17:19:26 SharedDb:   true
2024-05-29 17:19:26 shouldDelayTransientStatuses:       false
2024-05-29 17:19:26 CorsParams: null
2024-05-29 17:19:26 


```

**Comment by alnaranjo** [comment]
I'm experiencing the same. I reverted to 2.4.0 for now

**Comment by Jeffasaurus** [comment]
Experiencing the same in Windows.  Reverted to 2.4.0 for now as well.

**Comment by emilebourquin** [comment]
Also experiencing the same error on Windows with Docker Desktop.

**Comment by sktomer** [comment]
Please open this issue here: https://github.com/awslabs/amazon-dynamodb-local-samples/issues
This page is specifically for Amazon Linux provided container images.

**Comment by Maxwell2022** [comment]
@sktomer dockerhub has a single link that point to this repo. Someone should probably update it

**Comment by sktomer** [comment]
@Maxwell2022 could you please share the webpage where you found the link to this page ? meanwhile I'll reach out to dynamoDB team to set the right expectations.

**Comment by Maxwell2022** [comment]
Sorry, it seems I've dreamed about it, I cannot find this link anymore. I've created this issue in the repo you pointed out. Thanks for helping out.

**Comment by biagiopietro** [comment]
> Sorry, it seems I've dreamed about it

I see the link to this repo into `Dockerhub` under "Where to file issues"

- https://hub.docker.com/_/amazonlinux
<img width="592" alt="image" src="https://github.com/amazonlinux/container-images/assets/36191829/705bd288-3b4a-488d-8fdb-4aadf2b71393">
